# Generated by Django 4.2.20 on 2025-03-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedestrian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=225)),
                ('is_drunk', models.BooleanField(default=False)),
                ('bladder', models.IntegerField(default=0)),
                ('bowels', models.IntegerField(default=0)),
            ],
        ),
    ]
