# Generated by Django 4.2.20 on 2025-03-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('park', 'Park'), ('restaurant', 'Restaurant'), ('store', 'Store'), ('bar', 'Bar'), ('house', 'House'), ('apartment', 'Appartment'), ('gas_station', 'Gas Station'), ('office', 'Office')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('has_restroom', models.BooleanField(default=False)),
                ('open_now', models.BooleanField(default=True)),
                ('open_to_public', models.BooleanField(default=True)),
                ('hours_open', models.CharField(blank=True, help_text="For display, e.g., '9AM - 5PM'", max_length=50, null=True)),
            ],
        ),
    ]
