# Generated by Django 4.2.20 on 2025-03-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='subtype',
            field=models.IntegerField(blank=True, choices=[(1, 'Fancy'), (2, 'Average'), (3, 'Scuzzy')], help_text='Only applies to stores, bars, and restaurants', null=True),
        ),
    ]
