# Generated by Django 4.2.20 on 2025-03-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_location_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('toilet_meter_drain_rate', models.FloatField(help_text='Rate at which toilet meter depletese (lower = slower)')),
                ('sprite_url', models.CharField(max_length=255)),
            ],
        ),
    ]
