# Generated by Django 4.2.20 on 2025-04-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='follow_distance_max',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='character',
            name='follow_distance_min',
            field=models.IntegerField(default=30),
        ),
    ]
