# Generated by Django 4.2.20 on 2025-04-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0005_character_follow_distance_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='restroom_line',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='restroom_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='restroom_out_of_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='restroom_requires_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='restroom_visible',
            field=models.BooleanField(default=False),
        ),
    ]
