# Generated by Django 4.2.20 on 2025-04-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0006_location_restroom_line_location_restroom_occupied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='restroom_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='restroom_requires_code',
            field=models.BooleanField(default=False),
        ),
    ]
