# Generated by Django 4.2.20 on 2025-04-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0007_location_restroom_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_weights', models.JSONField(default=dict)),
                ('subtype_weights', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='subtype',
            field=models.IntegerField(blank=True, choices=[(1, 'Fancy'), (2, 'Nice'), (3, 'Average'), (4, 'Poor'), (5, 'Scuzzy')], help_text='Applies to all locations', null=True),
        ),
    ]
